version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "mytest-app"           # your existing ECR repo
    IMAGE_TAG: "prod"                       # tag App Runner tracks
  parameter-store: {}
  secrets-manager: {}

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'

